//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorClient.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.bit.ueh.edu.vn/", ConfigurationName="CalculatorService.CalculatorWs")]
    public interface CalculatorWs {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.bit.ueh.edu.vn/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/addRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/addResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorClient.CalculatorService.addResponse add(CalculatorClient.CalculatorService.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/addRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/addResponse")]
        System.Threading.Tasks.Task<CalculatorClient.CalculatorService.addResponse> addAsync(CalculatorClient.CalculatorService.addRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.bit.ueh.edu.vn/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/multiplyRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/multiplyResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorClient.CalculatorService.multiplyResponse multiply(CalculatorClient.CalculatorService.multiplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/multiplyRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/multiplyResponse")]
        System.Threading.Tasks.Task<CalculatorClient.CalculatorService.multiplyResponse> multiplyAsync(CalculatorClient.CalculatorService.multiplyRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.bit.ueh.edu.vn/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/subtractRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/subtractResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorClient.CalculatorService.subtractResponse subtract(CalculatorClient.CalculatorService.subtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/subtractRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/subtractResponse")]
        System.Threading.Tasks.Task<CalculatorClient.CalculatorService.subtractResponse> subtractAsync(CalculatorClient.CalculatorService.subtractRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.bit.ueh.edu.vn/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/divideRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/divideResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorClient.CalculatorService.divideResponse divide(CalculatorClient.CalculatorService.divideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/divideRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/divideResponse")]
        System.Threading.Tasks.Task<CalculatorClient.CalculatorService.divideResponse> divideAsync(CalculatorClient.CalculatorService.divideRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public addRequest() {
        }
        
        public addRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public addResponse() {
        }
        
        public addResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiply", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class multiplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public multiplyRequest() {
        }
        
        public multiplyRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplyResponse", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class multiplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public multiplyResponse() {
        }
        
        public multiplyResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subtract", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class subtractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public subtractRequest() {
        }
        
        public subtractRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subtractResponse", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class subtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public subtractResponse() {
        }
        
        public subtractResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divide", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class divideRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public divideRequest() {
        }
        
        public divideRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divideResponse", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class divideResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divideResponse() {
        }
        
        public divideResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWsChannel : CalculatorClient.CalculatorService.CalculatorWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWsClient : System.ServiceModel.ClientBase<CalculatorClient.CalculatorService.CalculatorWs>, CalculatorClient.CalculatorService.CalculatorWs {
        
        public CalculatorWsClient() {
        }
        
        public CalculatorWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorClient.CalculatorService.addResponse CalculatorClient.CalculatorService.CalculatorWs.add(CalculatorClient.CalculatorService.addRequest request) {
            return base.Channel.add(request);
        }
        
        public int add(int arg0, int arg1) {
            CalculatorClient.CalculatorService.addRequest inValue = new CalculatorClient.CalculatorService.addRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorClient.CalculatorService.addResponse retVal = ((CalculatorClient.CalculatorService.CalculatorWs)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorClient.CalculatorService.addResponse> CalculatorClient.CalculatorService.CalculatorWs.addAsync(CalculatorClient.CalculatorService.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorClient.CalculatorService.addResponse> addAsync(int arg0, int arg1) {
            CalculatorClient.CalculatorService.addRequest inValue = new CalculatorClient.CalculatorService.addRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorClient.CalculatorService.CalculatorWs)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorClient.CalculatorService.multiplyResponse CalculatorClient.CalculatorService.CalculatorWs.multiply(CalculatorClient.CalculatorService.multiplyRequest request) {
            return base.Channel.multiply(request);
        }
        
        public double multiply(double arg0, double arg1) {
            CalculatorClient.CalculatorService.multiplyRequest inValue = new CalculatorClient.CalculatorService.multiplyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorClient.CalculatorService.multiplyResponse retVal = ((CalculatorClient.CalculatorService.CalculatorWs)(this)).multiply(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorClient.CalculatorService.multiplyResponse> CalculatorClient.CalculatorService.CalculatorWs.multiplyAsync(CalculatorClient.CalculatorService.multiplyRequest request) {
            return base.Channel.multiplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorClient.CalculatorService.multiplyResponse> multiplyAsync(double arg0, double arg1) {
            CalculatorClient.CalculatorService.multiplyRequest inValue = new CalculatorClient.CalculatorService.multiplyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorClient.CalculatorService.CalculatorWs)(this)).multiplyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorClient.CalculatorService.subtractResponse CalculatorClient.CalculatorService.CalculatorWs.subtract(CalculatorClient.CalculatorService.subtractRequest request) {
            return base.Channel.subtract(request);
        }
        
        public int subtract(int arg0, int arg1) {
            CalculatorClient.CalculatorService.subtractRequest inValue = new CalculatorClient.CalculatorService.subtractRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorClient.CalculatorService.subtractResponse retVal = ((CalculatorClient.CalculatorService.CalculatorWs)(this)).subtract(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorClient.CalculatorService.subtractResponse> CalculatorClient.CalculatorService.CalculatorWs.subtractAsync(CalculatorClient.CalculatorService.subtractRequest request) {
            return base.Channel.subtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorClient.CalculatorService.subtractResponse> subtractAsync(int arg0, int arg1) {
            CalculatorClient.CalculatorService.subtractRequest inValue = new CalculatorClient.CalculatorService.subtractRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorClient.CalculatorService.CalculatorWs)(this)).subtractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorClient.CalculatorService.divideResponse CalculatorClient.CalculatorService.CalculatorWs.divide(CalculatorClient.CalculatorService.divideRequest request) {
            return base.Channel.divide(request);
        }
        
        public double divide(double arg0, double arg1) {
            CalculatorClient.CalculatorService.divideRequest inValue = new CalculatorClient.CalculatorService.divideRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorClient.CalculatorService.divideResponse retVal = ((CalculatorClient.CalculatorService.CalculatorWs)(this)).divide(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorClient.CalculatorService.divideResponse> CalculatorClient.CalculatorService.CalculatorWs.divideAsync(CalculatorClient.CalculatorService.divideRequest request) {
            return base.Channel.divideAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorClient.CalculatorService.divideResponse> divideAsync(double arg0, double arg1) {
            CalculatorClient.CalculatorService.divideRequest inValue = new CalculatorClient.CalculatorService.divideRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorClient.CalculatorService.CalculatorWs)(this)).divideAsync(inValue);
        }
    }
}
